// <auto-generated />Carros
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api6969.Context;

#nullable disable

namespace api6969.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240328163919_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api6969.Models.Carro", b =>
                {
                    b.Property<string>("chassi")
                        .HasColumnType("text");

                    b.Property<int>("ano")
                        .HasColumnType("integer");

                    b.Property<string>("cambio")
                        .HasColumnType("text");

                    b.Property<string>("combustivel")
                        .HasColumnType("text");

                    b.Property<string>("cor")
                        .HasColumnType("text");

                    b.Property<string>("marca")
                        .HasColumnType("text");

                    b.Property<string>("modelo")
                        .HasColumnType("text");

                    b.Property<string>("motor")
                        .HasColumnType("text");

                    b.HasKey("chassi");

                    b.ToTable("Carros");
                });
#pragma warning restore 612, 618
        }
    }
}
